<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TestingPackage" nsURI="TestingMM" nsPrefix="TestingMM">
  <eClassifiers xsi:type="ecore:EClass" name="TestCampaign">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" upperBound="-1"
        eType="#//Test" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attacks" upperBound="-1"
        eType="#//Attack" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attack">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topicToAttackString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topicToAttack" eType="ecore:EClass http://ExSceMM#//Topic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeToAttack" eType="ecore:EClass http://ExSceMM#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceAttack" eSuperTypes="#//Attack"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateAttack" eSuperTypes="#//Attack"/>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkAttack" eSuperTypes="#//Attack"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoadResourceAttack" eSuperTypes="#//ResourceAttack">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loadType" lowerBound="1"
        eType="#//LoadType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CPULoadType" eSuperTypes="#//LoadType"/>
  <eClassifiers xsi:type="ecore:EClass" name="MemoryLoadType" eSuperTypes="#//LoadType"/>
  <eClassifiers xsi:type="ecore:EClass" name="IOLoadType" eSuperTypes="#//LoadType"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiskLoadType" eSuperTypes="#//LoadType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ShutdownStateAttack" eSuperTypes="#//StateAttack"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeTravelStateAttack" eSuperTypes="#//StateAttack"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessKillerStateAttack" eSuperTypes="#//StateAttack"/>
  <eClassifiers xsi:type="ecore:EClass" name="BlackholeNetworkAttack" eSuperTypes="#//NetworkAttack"/>
  <eClassifiers xsi:type="ecore:EClass" name="LatencyNetworkAttack" eSuperTypes="#//NetworkAttack"/>
  <eClassifiers xsi:type="ecore:EClass" name="PacketLossNetworkAttack" eSuperTypes="#//NetworkAttack">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleMessagesNetworkAttack" eSuperTypes="#//NetworkAttack"/>
</ecore:EPackage>
