<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ecore:EPackage xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="jetbrains.mps.samples.StateChart" nsPrefix="jetbrains.mps.samples.StateChart" nsURI="org.example.jetbrains.mps.samples.StateChart" xmi:version="2.0">
    <eClassifiers eSuperTypes="#//Stateful " name="StateChart" xsi:type="ecore:EClass">
        <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" name="name" xsi:type="ecore:EAttribute"/>
    </eClassifiers>
    <eClassifiers name="Event" xsi:type="ecore:EClass">
        <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" name="name" xsi:type="ecore:EAttribute"/>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//Stateful " name="State" xsi:type="ecore:EClass">
        <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" name="name" xsi:type="ecore:EAttribute"/>
        <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" name="isInitial" xsi:type="ecore:EAttribute"/>
        <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" name="isFinal" xsi:type="ecore:EAttribute"/>
        <eStructuralFeatures containment="true" eType="#//Transition" name="transitions" upperBound="-1" xsi:type="ecore:EReference"/>
        <eStructuralFeatures containment="true" eType="#//OperationsList" lowerBound="1" name="onEntry" xsi:type="ecore:EReference"/>
        <eStructuralFeatures containment="true" eType="#//OperationsList" lowerBound="1" name="onExit" xsi:type="ecore:EReference"/>
    </eClassifiers>
    <eClassifiers name="Transition" xsi:type="ecore:EClass">
        <eStructuralFeatures containment="true" eType="#//OperationsList" lowerBound="1" name="onTransit" xsi:type="ecore:EReference"/>
        <eStructuralFeatures eType="#//Event" lowerBound="1" name="trigger" xsi:type="ecore:EReference"/>
        <eStructuralFeatures eType="#//State" lowerBound="1" name="target" xsi:type="ecore:EReference"/>
    </eClassifiers>
    <eClassifiers name="ChartOperation" xsi:type="ecore:EClass"/>
    <eClassifiers eSuperTypes="#//ChartOperation " name="Raise" xsi:type="ecore:EClass">
        <eStructuralFeatures eType="#//Event" lowerBound="1" name="event" xsi:type="ecore:EReference"/>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//ChartOperation " name="Log" xsi:type="ecore:EClass">
        <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" name="value" xsi:type="ecore:EAttribute"/>
    </eClassifiers>
    <eClassifiers name="OperationsList" xsi:type="ecore:EClass">
        <eStructuralFeatures containment="true" eType="#//ChartOperation" name="operations" upperBound="-1" xsi:type="ecore:EReference"/>
    </eClassifiers>
    <eClassifiers eSuperTypes="#//ChartOperation " name="EmptyOperation" xsi:type="ecore:EClass"/>
    <eClassifiers name="ScopeProvider" xsi:type="ecore:EClass"/>
    <eClassifiers eSuperTypes="#//ScopeProvider " name="Stateful" xsi:type="ecore:EClass">
        <eStructuralFeatures containment="true" eType="#//Event" name="availableTriggers" upperBound="-1" xsi:type="ecore:EReference"/>
        <eStructuralFeatures containment="true" eType="#//State" name="states" upperBound="-1" xsi:type="ecore:EReference"/>
    </eClassifiers>
</ecore:EPackage>
