<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TestingPackage" nsURI="TestingMM" nsPrefix="TestingMM">
  <eClassifiers xsi:type="ecore:EClass" name="TestCampaign">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" upperBound="-1"
        eType="#//Test" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" upperBound="-1"
        eType="#//Metrics/Metric" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="possibleAttacks" upperBound="-1"
        eType="#//Attacks/Attack" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestGenerationApproach" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reTrigger" lowerBound="1"
        eType="#//TestCampaign"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomTestGeneration" eSuperTypes="#//TestGenerationApproach"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attacks" upperBound="-1"
        eType="#//Attacks/Attack"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" upperBound="-1"
        eType="#//Metrics/Metric"/>
  </eClassifiers>
  <eSubpackages name="Attacks" nsURI="Attacks" nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="Attack">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attackTimes" upperBound="-1"
          eType="#//Attacks/AttackTime" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="topicToAttack" eType="ecore:EClass http://ExSceMM#//Topic"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="messagesFromAllComponenents"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fromNodes" upperBound="-1"
          eType="ecore:EClass http://ExSceMM#//Node"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="messagesToAllComponenents"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="toNodes" upperBound="-1"
          eType="ecore:EClass http://ExSceMM#//Node"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodeToAttack" eType="ecore:EClass http://ExSceMM#//Node"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="allPublishingTopics"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="publishingTopics" upperBound="-1"
          eType="ecore:EClass http://ExSceMM#//Topic"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="allSubscribingTopics"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subscribingTopics" upperBound="-1"
          eType="ecore:EClass http://ExSceMM#//Topic"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="next" lowerBound="1"
          eType="#//Attacks/Attack"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OfflineAttack" eSuperTypes="#//Attacks/Attack">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="attackTime" eType="#//Attacks/OfflineAttackTime"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="OfflineAttackTime">
      <eLiterals name="PRE"/>
      <eLiterals name="POST" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomAttack" eSuperTypes="#//Attacks/Attack"/>
    <eClassifiers xsi:type="ecore:EClass" name="CustomOfflineAttack" eSuperTypes="#//Attacks/OfflineAttack"/>
    <eClassifiers xsi:type="ecore:EClass" name="AttackTime">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FuzzTestingAttack" eSuperTypes="#//Attacks/Attack"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentAttack" eSuperTypes="#//Attacks/FuzzTestingAttack"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentPropertyAttack" eSuperTypes="#//Attacks/FuzzTestingAttack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="propertyToAttack" eType="ecore:EClass http://ExSceMM#//ComponentProperty"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentSubPropertyAttack" eSuperTypes="#//Attacks/FuzzTestingAttack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="propertyToAttack" eType="ecore:EClass http://ExSceMM#//ComponentProperty"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subProperty" eType="ecore:EClass http://ExSceMM#//Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TopicAttack" eSuperTypes="#//Attacks/FuzzTestingAttack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subParameters" upperBound="-1"
          eType="ecore:EClass http://ExSceMM#//Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RandomValueAttack" eSuperTypes="#//Attacks/ComponentPropertyAttack">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="seed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RandomValueFromSetAttack" eSuperTypes="#//Attacks/RandomValueAttack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="valueSet" upperBound="-1"
          eType="#//Attacks/ValueSet" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValueSet"/>
    <eClassifiers xsi:type="ecore:EClass" name="ValueRange" eSuperTypes="#//Attacks/ValueSet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntRange" eSuperTypes="#//Attacks/ValueRange">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DoubleRange" eSuperTypes="#//Attacks/ValueRange">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringRange" eSuperTypes="#//Attacks/ValueRange">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalResourceSet" eSuperTypes="#//Attacks/ValueSet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceAttack" eSuperTypes="#//Attacks/Attack"/>
    <eClassifiers xsi:type="ecore:EClass" name="StateAttack" eSuperTypes="#//Attacks/Attack"/>
    <eClassifiers xsi:type="ecore:EClass" name="NetworkAttack" eSuperTypes="#//Attacks/Attack"/>
    <eClassifiers xsi:type="ecore:EClass" name="LoadResourceAttack" eSuperTypes="#//Attacks/ResourceAttack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="loadType" lowerBound="1"
          eType="#//Attacks/LoadType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoadType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CPULoadType" eSuperTypes="#//Attacks/LoadType"/>
    <eClassifiers xsi:type="ecore:EClass" name="MemoryLoadType" eSuperTypes="#//Attacks/LoadType"/>
    <eClassifiers xsi:type="ecore:EClass" name="IOLoadType" eSuperTypes="#//Attacks/LoadType"/>
    <eClassifiers xsi:type="ecore:EClass" name="DiskLoadType" eSuperTypes="#//Attacks/LoadType"/>
    <eClassifiers xsi:type="ecore:EClass" name="ShutdownStateAttack" eSuperTypes="#//Attacks/StateAttack"/>
    <eClassifiers xsi:type="ecore:EClass" name="TimeTravelStateAttack" eSuperTypes="#//Attacks/StateAttack">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeTravelValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessKillerStateAttack" eSuperTypes="#//Attacks/StateAttack">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="processId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlackholeNetworkAttack" eSuperTypes="#//Attacks/NetworkAttack"/>
    <eClassifiers xsi:type="ecore:EClass" name="LatencyNetworkAttack" eSuperTypes="#//Attacks/NetworkAttack">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="latency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PacketLossNetworkAttack" eSuperTypes="#//Attacks/NetworkAttack">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MultipleMessagesNetworkAttack" eSuperTypes="#//Attacks/NetworkAttack">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="howManyClones" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Metrics" nsURI="Metrics" nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="Metric">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="asStream" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="passed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="feedback" lowerBound="1"
          eType="#//TestGenerationApproach"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relatedTopics" upperBound="-1"
          eType="ecore:EClass http://ExSceMM#//Topic"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
          eType="#//Results/Result"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyMetric" abstract="true" eSuperTypes="#//Metrics/Metric">
      <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
          eType="ecore:EClass http://ExSceMM#//ComponentProperty"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionalPropertyMetric" eSuperTypes="#//Metrics/PropertyMetric">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComplexMetric" eSuperTypes="#//Metrics/Metric">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementationClass"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Results" nsURI="Results" nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="Result">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
