<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TestingPackage" nsURI="TestingMM" nsPrefix="TestingMM">
  <eClassifiers xsi:type="ecore:EClass" name="TestingSpace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" upperBound="-1"
        eType="#//Metrics/Metric" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="possibleAttacks" upperBound="-1"
        eType="#//Attacks/Attack" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="grammarSpecification" eType="#//GrammarSpec/GrammarSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="campaigns" upperBound="-1"
        eType="#//TestCampaign" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mrs" lowerBound="1" eType="#//MRSPackage/MRS"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestCampaign">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" upperBound="-1"
        eType="#//Metrics/Metric"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includedAttacks" upperBound="-1"
        eType="#//Attacks/Attack"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//GrammarSpec/GrammarConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="approach" lowerBound="1"
        eType="#//TestGenerationApproach" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="performedTests" upperBound="-1"
        eType="#//Test" containment="true" eOpposite="#//Test/parentCampaign"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultSets" upperBound="-1"
        eType="#//CampaignResultSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultEndTrigger" lowerBound="1"
        eType="#//ExecutionEndTrigger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attacks" upperBound="-1"
        eType="#//Attacks/Attack" containment="true" eOpposite="#//Attacks/Attack/containingTest"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" upperBound="-1"
        eType="#//Metrics/MetricInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endTrigger" lowerBound="1"
        eType="#//ExecutionEndTrigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="developedFrom" upperBound="-1"
        eType="#//Test"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentCampaign" lowerBound="1"
        eType="#//TestCampaign" changeable="false" transient="true" eOpposite="#//TestCampaign/performedTests"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ResultSetStatus">
    <eLiterals name="FINAL" value="1"/>
    <eLiterals name="INTERMEDIATE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CampaignResultSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//ResultSetStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
        eType="#//Test"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionEndTrigger" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeBasedEnd" eSuperTypes="#//ExecutionEndTrigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeLimitSeconds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestGenerationApproach" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RandomTestGeneration" eSuperTypes="#//TestGenerationApproach"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvolutionaryAlgorithm" abstract="true"
      eSuperTypes="#//TestGenerationApproach"/>
  <eClassifiers xsi:type="ecore:EClass" name="NSGAEvolutionaryAlgorithm" eSuperTypes="#//EvolutionaryAlgorithm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="populationSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iterations" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eSubpackages name="Attacks" nsURI="Attacks" nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="Attack">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attackActivation" upperBound="-1"
          eType="#//Attacks/AttackActivation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="topicToAttack" eType="#//MRSPackage/Topic"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="messagesFromAllComponenents"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fromNodes" upperBound="-1"
          eType="#//MRSPackage/Node"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="messagesToAllComponenents"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="toNodes" upperBound="-1"
          eType="#//MRSPackage/Node"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodeToAttack" eType="#//MRSPackage/Node"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="allPublishingTopics"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="publishingTopics" upperBound="-1"
          eType="#//MRSPackage/Topic"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="allSubscribingTopics"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subscribingTopics" upperBound="-1"
          eType="#//MRSPackage/Topic"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fromTemplate" eType="#//Attacks/Attack"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containingTest" eType="#//Test"
          changeable="false" transient="true" eOpposite="#//Test/attacks"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OfflineAttack" eSuperTypes="#//Attacks/Attack">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="attackTime" eType="#//Attacks/OfflineAttackTime"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="OfflineAttackTime">
      <eLiterals name="PRE"/>
      <eLiterals name="POST" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomAttack" eSuperTypes="#//Attacks/Attack"/>
    <eClassifiers xsi:type="ecore:EClass" name="CustomOfflineAttack" eSuperTypes="#//Attacks/OfflineAttack"/>
    <eClassifiers xsi:type="ecore:EClass" name="AttackActivation" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="AttackFixedTime" eSuperTypes="#//Attacks/AttackActivation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionBased" eSuperTypes="#//Attacks/AttackActivation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="starting" eType="#//Conditions/Condition"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ending" eType="#//Conditions/Condition"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FuzzTestingAttack" eSuperTypes="#//Attacks/Attack"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentAttack" eSuperTypes="#//Attacks/FuzzTestingAttack"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentPropertyAttack" eSuperTypes="#//Attacks/FuzzTestingAttack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="propertyToAttack" eType="#//MRSPackage/ComponentProperty"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentSubPropertyAttack" eSuperTypes="#//Attacks/FuzzTestingAttack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="propertyToAttack" eType="#//MRSPackage/ComponentProperty"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subProperty" eType="#//MRSPackage/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TopicAttack" eSuperTypes="#//Attacks/FuzzTestingAttack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subParameters" upperBound="-1"
          eType="#//MRSPackage/Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RandomValueAttack" eSuperTypes="#//Attacks/ComponentPropertyAttack">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="seed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RandomValueFromSetAttack" eSuperTypes="#//Attacks/RandomValueAttack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="valueSet" upperBound="-1"
          eType="#//Attacks/ValueSet" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValueSet"/>
    <eClassifiers xsi:type="ecore:EClass" name="ValueRange" eSuperTypes="#//Attacks/ValueSet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntRange" eSuperTypes="#//Attacks/ValueRange">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DoubleRange" eSuperTypes="#//Attacks/ValueRange">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringRange" eSuperTypes="#//Attacks/ValueRange">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalResourceSet" eSuperTypes="#//Attacks/ValueSet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourceAttack" eSuperTypes="#//Attacks/Attack"/>
    <eClassifiers xsi:type="ecore:EClass" name="StateAttack" eSuperTypes="#//Attacks/Attack"/>
    <eClassifiers xsi:type="ecore:EClass" name="NetworkAttack" eSuperTypes="#//Attacks/Attack"/>
    <eClassifiers xsi:type="ecore:EClass" name="LoadResourceAttack" eSuperTypes="#//Attacks/ResourceAttack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="loadType" lowerBound="1"
          eType="#//Attacks/LoadType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoadType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CPULoadType" eSuperTypes="#//Attacks/LoadType"/>
    <eClassifiers xsi:type="ecore:EClass" name="MemoryLoadType" eSuperTypes="#//Attacks/LoadType"/>
    <eClassifiers xsi:type="ecore:EClass" name="IOLoadType" eSuperTypes="#//Attacks/LoadType"/>
    <eClassifiers xsi:type="ecore:EClass" name="DiskLoadType" eSuperTypes="#//Attacks/LoadType"/>
    <eClassifiers xsi:type="ecore:EClass" name="ShutdownStateAttack" eSuperTypes="#//Attacks/StateAttack"/>
    <eClassifiers xsi:type="ecore:EClass" name="TimeTravelStateAttack" eSuperTypes="#//Attacks/StateAttack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="timeTravelValue" lowerBound="1"
          eType="#//Attacks/DoubleRange" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessKillerStateAttack" eSuperTypes="#//Attacks/StateAttack">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="processId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlackholeNetworkAttack" eSuperTypes="#//Attacks/NetworkAttack"/>
    <eClassifiers xsi:type="ecore:EClass" name="LatencyNetworkAttack" eSuperTypes="#//Attacks/NetworkAttack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="latency" lowerBound="1"
          eType="#//Attacks/DoubleRange" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PacketLossNetworkAttack" eSuperTypes="#//Attacks/NetworkAttack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="frequency" lowerBound="1"
          eType="#//Attacks/DoubleRange" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MultipleMessagesNetworkAttack" eSuperTypes="#//Attacks/NetworkAttack">
      <eStructuralFeatures xsi:type="ecore:EReference" name="howManyClones" lowerBound="1"
          eType="#//Attacks/IntRange" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Metrics" nsURI="Metrics" nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="SimStream" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="InputStream" eSuperTypes="#//Metrics/SimStream"/>
    <eClassifiers xsi:type="ecore:EClass" name="OutputStream" eSuperTypes="#//Metrics/SimStream"/>
    <eClassifiers xsi:type="ecore:EEnum" name="MetricOptimisationDirection">
      <eLiterals name="HIGHEST" value="1"/>
      <eLiterals name="LOWEST" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="MetricStateKeyedBy">
      <eLiterals name="TEST" value="1"/>
      <eLiterals name="TOPIC" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Metric" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dir" eType="#//Metrics/MetricOptimisationDirection"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyedBy" eType="#//Metrics/MetricStateKeyedBy"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relatedTopics" upperBound="-1"
          eType="#//MRSPackage/Topic"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//Metrics/MetricDefault"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MetricDefault">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultVal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TopicMetric" eSuperTypes="#//Metrics/Metric">
      <eStructuralFeatures xsi:type="ecore:EReference" name="chosenTopics" lowerBound="1"
          eType="#//MRSPackage/Topic"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MetricInstance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="metric" lowerBound="1"
          eType="#//Metrics/Metric"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="result" lowerBound="1"
          eType="#//Results/Result" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyMetric" abstract="true" eSuperTypes="#//Metrics/Metric">
      <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
          eType="#//MRSPackage/ComponentProperty"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConditionalPropertyMetric" eSuperTypes="#//Metrics/PropertyMetric">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StreamMetric" eSuperTypes="#//Metrics/Metric">
      <eStructuralFeatures xsi:type="ecore:EReference" name="streams" upperBound="-1"
          eType="#//Metrics/SimStream" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="res" eType="#//Metrics/StreamResult"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AttackTimesMetric" eSuperTypes="#//Metrics/StreamMetric"/>
    <eClassifiers xsi:type="ecore:EClass" name="StreamResult" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="FileStreamResult" eSuperTypes="#//Metrics/StreamResult">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Results" nsURI="Results" nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="Result">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Conditions" nsURI="Conditions" nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="Condition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elt" lowerBound="1" eType="#//Conditions/Node"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Node">
      <eStructuralFeatures xsi:type="ecore:EReference" name="grammarElt" lowerBound="1"
          eType="#//GrammarSpec/GrammarElt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subNodes" upperBound="-1"
          eType="#//Conditions/Node" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//Conditions/NodeValue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NodeValue" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IntNodeValue" eSuperTypes="#//Conditions/NodeValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringNodeValue" eSuperTypes="#//Conditions/NodeValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DoubleNodeValue" eSuperTypes="#//Conditions/NodeValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="GrammarSpec" nsURI="GrammarSpec" nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="GrammarSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rootElement" lowerBound="1"
          eType="#//GrammarSpec/GrammarElt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
          eType="#//GrammarSpec/GrammarElt" containment="true" eOpposite="#//GrammarSpec/GrammarElt/parentGrammar"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
          eType="#//GrammarSpec/GrammarRule" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GrammarTag">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GrammarElt" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentGrammar" lowerBound="1"
          eType="#//GrammarSpec/GrammarSpecification" changeable="false" transient="true"
          eOpposite="#//GrammarSpec/GrammarSpecification/elements"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NonterminalGrammarElt" eSuperTypes="#//GrammarSpec/GrammarElt"/>
    <eClassifiers xsi:type="ecore:EClass" name="TerminalGrammarElt" eSuperTypes="#//GrammarSpec/GrammarElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//GrammarSpec/GrammarValue" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GrammarValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="object" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GrammarRhsElt">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elt" lowerBound="1" eType="#//GrammarSpec/GrammarElt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GrammarRule">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//GrammarSpec/NonterminalGrammarElt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rhsElts" upperBound="-1"
          eType="#//GrammarSpec/GrammarRhsElt" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GrammarConstraint"/>
  </eSubpackages>
  <eSubpackages name="StandardGrammar" nsURI="StandardGrammar" nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="SimulatorVariable" eSuperTypes="#//StandardGrammar/Variable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" eSuperTypes="#//StandardGrammar/Expression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//StandardGrammar/Expression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//StandardGrammar/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BinaryComparator">
      <eLiterals name="LESS_THAN" value="1"/>
      <eLiterals name="GREATER_THAN" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BinaryLogicalOperation">
      <eLiterals name="AND" value="1"/>
      <eLiterals name="OR" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryComparison" eSuperTypes="#//StandardGrammar/BinaryExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="comp" eType="#//StandardGrammar/BinaryComparator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryLogicalExpression" eSuperTypes="#//StandardGrammar/BinaryExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="binOp" eType="#//StandardGrammar/BinaryLogicalOperation"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="MRSPackage" nsURI="MRSPackage" nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="MRS">
      <eStructuralFeatures xsi:type="ecore:EReference" name="topics" upperBound="-1"
          eType="#//MRSPackage/Topic" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="launchFileLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
          eType="#//MRSPackage/Node" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="simulator" lowerBound="1"
          eType="#//MRSPackage/Simulator" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="propertyType" upperBound="-1"
          eType="#//MRSPackage/Type" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Node">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subscriber" upperBound="-1"
          eType="#//MRSPackage/Topic"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="publisher" upperBound="-1"
          eType="#//MRSPackage/Topic"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//MRSPackage/ComponentProperty"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Topic">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//MRSPackage/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parsingMethod" lowerBound="1"
          eType="#//MRSPackage/ParsingMethod"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//MRSPackage/Parameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ParsingMethod">
      <eLiterals name="JSON"/>
      <eLiterals name="CSV" value="1"/>
      <eLiterals name="CUSTOM" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subparameters" upperBound="-1"
          eType="#//MRSPackage/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//MRSPackage/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentProperty">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//MRSPackage/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Simulator" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ROSSimulator" eSuperTypes="#//MRSPackage/Simulator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MOOSSimulator" eSuperTypes="#//MRSPackage/Simulator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TTSSimulator" eSuperTypes="#//MRSPackage/Simulator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hostname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
